In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('E:\\pycharm项目\\data_analysis\\data\\23 L2W1-优衣库数据.csv')
df

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,658,深圳,线下,Female,25-29,Weekday,当季新品,4,796.0,4,4,59
1,146,杭州,线下,Female,25-29,Weekday,运动,1,149.0,1,1,49
2,70,深圳,线下,Male,>=60,Weekday,T恤,2,178.0,2,2,49
3,658,深圳,线下,Female,25-29,Weekday,T恤,1,59.0,1,1,49
4,229,深圳,线下,Male,20-24,Weekend,袜子,2,65.0,2,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...
22288,146,杭州,线下,Female,30-34,Weekday,短裤,1,80.0,1,2,19
22289,430,成都,线下,Female,25-29,Weekend,T恤,1,79.0,1,1,49
22290,449,武汉,线下,Female,35-39,Weekday,T恤,1,158.0,1,2,49
22291,758,杭州,线下,Female,20-24,Weekday,袜子,1,26.0,1,1,9
22292,616,成都,线下,Male,30-34,Weekday,当季新品,1,79.0,1,1,59

# 1.交叉表（了解）

# 2.透视表（掌握）

观察下面可见：透视表是对分组聚合的进一步优化，即在将数据集以表格的形式显示出来，更好地表示某一列与另一列的关系

In [4]:
df.groupby(['city', 'channel']).agg({
    'revenue':'sum'
})

                revenue
city channel
上海   线上       114438.09
     线下       275383.64
北京   线下       130458.62
南京   线下       123150.93
广州   线上       200893.30
     线下       117231.19
成都   线下       208189.86
杭州   线下       589518.49
武汉   线上       281420.73
     线下       308357.05
深圳   线下       733123.68
西安   线上        30088.01
     线下       180686.61
重庆   线上        26330.35
     线下       237162.30

In [3]:
df.pivot_table(index = 'city', columns = 'channel', values = 'revenue', aggfunc = 'sum')

channel         线上         线下
city
上海       114438.09  275383.64
北京             NaN  130458.62
南京             NaN  123150.93
广州       200893.30  117231.19
成都             NaN  208189.86
杭州             NaN  589518.49
武汉       281420.73  308357.05
深圳             NaN  733123.68
西安        30088.01  180686.61
重庆        26330.35  237162.30